language: java
sudo: false
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches
after_success:
  - bash <(curl -s https://codecov.io/bash)
