language: java
sudo: false
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - curl -o codacy.jar https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/2.0.0/codacy-coverage-reporter-2.0.0-assembly.jar
  - java -cp codacy.jar com.codacy.CodacyCoverageReporter -l Java -r ./build/reports/jacoco/test/jacocoTestReport.xml
