package org.openehr.referencemodels;

public enum ModelDifferenceType {
    CLASS_MISSING_IN_BMM, CLASS_MISSING_IN_MODEL,
    PROPERTY_MISSING_IN_BMM, PROPERTY_MISSING_IN_MODEL,
    EXISTENCE_DIFFERENCE,
    ANCESTOR_DIFFERENCE,
    TYPE_NAME_DIFFERENCE,
    CARDINALITY_DIFFERENCE, ABSTRACT_DIFFERENCE;
}
